main: io.github.zaynstir.locator.Locator
name: Locator
version: 1
author: Zaynstir
authors: [Zaynstir, Peaceyo]
api-version: 1.15

commands:
  locator:
    description: overall tool to track deserters.