main: me.Zaynstir.Bounty.Main
name: Locator
version: 1
author: Zaynstir
authors: [Zaynstir, Peaceyo]
api-version: 1.15.2

commands:
  locator:
    description: overall tool to track deserters.